s:
	ssh -i ~/.ssh/id_geni_ssh_rsa e2093839@pc3.instageni.colorado.edu -p 27814
rsub_s:
	ssh -R 52698:localhost:52698 e2093839@pc3.instageni.colorado.edu -p 27814

r1:
	ssh -i ~/.ssh/id_geni_ssh_rsa e2093839@pc3.instageni.colorado.edu -p 27811
rsub_r1:
	ssh -R 52698:localhost:52698 e2093839@pc3.instageni.colorado.edu -p 27811

r2:
	ssh -i ~/.ssh/id_geni_ssh_rsa e2093839@pc3.instageni.colorado.edu -p 27812
rsub_r2:
	ssh -R 52698:localhost:52698 e2093839@pc3.instageni.colorado.edu -p 27812

r3:
	ssh -i ~/.ssh/id_geni_ssh_rsa e2093839@pc3.instageni.colorado.edu -p 27813
rsub_r3:
	ssh -R 52698:localhost:52698 e2093839@pc3.instageni.colorado.edu -p 27813

d:
	ssh -i ~/.ssh/id_geni_ssh_rsa e2093839@pc3.instageni.colorado.edu -p 27810
rsub_d:
	ssh -R 52698:localhost:52698 e2093839@pc3.instageni.colorado.edu -p 27810


